### PR TITLE
Rename get_marketsummary to get_market_summary

### PR DESCRIPTION
**Pull request by codesw1tch**
- Addresses #125 
- rename `get_marketsummary` to `get_market_summary` to be consistent with `get_market_summaries` naming convention

### CODE REVIEW

**Comment by codesw1tch** [comment]
@ericsomdahl This is a breaking change, so might warrant a major version bump? Let me know if you'd like me to change that in the codebase... `0.2.2` > `1.0.0` in `setup.py`?

**Comment by ericsomdahl** [comment]
@codesw1tch i don't think we'll ever get to 1.0 😃   Maybe when the websocket code finally lands. 

Bumping to 0.3.0 will be perfect for this.

**Comment by codesw1tch** [comment]
@ericsomdahl Makes sense :) wasn't sure if you were using semantic versioning on the project. Bumped to `0.3.0`!

**Comment by skyl** [comment]
Breaking changes are allowed in semantic versioning during 0.X 😉

**Comment by codesw1tch** [comment]
@skyl 

https://semver.org/

> MINOR version when you add functionality in a backwards-compatible manner, and

**Pull request merged**
