### PR TITLE
Create method get tick candle

### PR DESCRIPTION
**Pull request by bcolombini**
Create method get tick candle

### CODE REVIEW

**Comment by ericsomdahl** [comment]
@bcolombini hi, and thanks for this!

I have been thinking about how to integrate the V2 api workings into the current codebase.  There are many more methods to add from 2.0 and I do not believe that this is the best approach for a general solution.

There is a lot of overlap between the 2 APIs where just the base_url needs to change. What I had in mind was 

1. Add a parameter to the Bittrex() constructor specifying a minimum API version to attempt to use
1. changing the method signatures for the different endpoint calls (such as get_markets) to add an optional kwarg specifying an override of the minimum API version.
1. changing the different API methods to know their minimum and maximum API versions
1. For calls that are only in 2.0 the minimum version specified is ignored and 2.0 is forced
1. If an API method is called whose Max API version is less than the default (ie max 1.1 and min version is specified as 2.0) then that method should throw a runtime exception

**Comment by bcolombini** [comment]
i Think if choose version on construct and if i need v1 method , I will need new Bittrex instance. In my opinion it’s not better approach. But your idea is good, If I can help i will stay here. I will try add new methods for expand api.

Thanks

**Comment by ericsomdahl** [comment]
I have pushed a new branch out with some of these ideas, it is a work in
progress but you can see where I am going.

Please Take a look the api-2.0-support branch and let me know what you
think.

**Comment by ericsomdahl** [comment]
this is integraated in #62

**Comment by bcolombini** [comment]
I will see the new branch!

**Pull request closed without merging**
